### ISSUE TITLE
kubectl exec [POD] [COMMAND] is DEPRECATED というメッセージ

### ISSUE THREAD

**Issue by ftnext** [shibuiwilliam/ml-system-in-actions#12]
6章を読んでいますが、大変参考になっています。ありがとうございます。

手を動かしながら読んでいたところ、kubectl execコマンド実行でdeprecatedと表示されることに気づきましたので、共有します

## 環境

- macOS Mojave
- kubectl (client) 1.22

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
```

## 事象

`kubectl -n shadow-ab exec -it pod/client bash` を実行したところ、以下のメッセージが表示されました

>kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.

## 提案

`kubectl -n shadow-ab exec -it pod/client -- bash` への変更を提案します。

ざっと見たところchapter6で`kubectl exec`を使っているようですので、`--`を使ったコマンドに書き直すのがよさそうです。

## 参考

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#exec

https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/#getting-a-shell-to-a-container
>Note: The double dash (--) separates the arguments you want to pass to the command from the kubectl arguments. 

kubectlのどのバージョンからdouble dashを推奨するようになったのかは調べきれていません

**Comment by shibuiwilliam** [comment]
ありがとうございます。別途確認して修正します。

**Comment by shibuiwilliam** [comment]
遅くなりましたがアップデートしました。
