### ISSUE TITLE
Warning: using deprecated setting "mirrorPercent", use "mirrorPercentage" instead

### ISSUE THREAD

**Issue by ftnext** [shibuiwilliam/ml-system-in-actions#13]
shadow ab test patternを試したところ、warningメッセージが表示されましたので共有します。
shadow ab test patternは手元の環境で問題なく動作しました

## 環境

- macOS Mojave
- minikube version: v1.23.2
- kubectl (client) 1.22

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
```

```
$ istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (1 proxies)
```

## 事象

`make deploy`を実行したところ、表題のwarningが表示されました

## 提案

VirtualServiceの定義のうち以下の箇所を
https://github.com/shibuiwilliam/ml-system-in-actions/blob/4fb1b3e53e4ed7c36e82f7d4b5570e3959aef525/chapter6_operation_management/shadow_ab_pattern/manifests/deployment.yml#L228-L231

以下のように変更することでwarningは出なくなりました

```yml
 mirror: 
   host: iris 
   subset: rf 
 mirrorPercentage:
    value: 100
```

## 参考

- https://istio.io/latest/docs/tasks/traffic-management/mirroring/
- https://github.com/istio/istio/issues/32884

**Comment by shibuiwilliam** [comment]
ありがとうございます。別途確認して修正します。

**Comment by shibuiwilliam** [comment]
遅くなりましたがアップデートしました。
